-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.brands (
  brand_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  brand_name text NOT NULL,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT brands_pkey PRIMARY KEY (brand_id),
  CONSTRAINT brands_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.categories (
  category_name character varying NOT NULL,
  slug character varying,
  description text,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  category_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  organization_id uuid NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY (category_id),
  CONSTRAINT categories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.client_transactions (
  transaction_id bigint NOT NULL DEFAULT nextval('client_transactions_transaction_id_seq'::regclass),
  client_id bigint NOT NULL,
  order_id bigint,
  transaction_type USER-DEFINED NOT NULL CHECK (transaction_type::text = ANY (ARRAY['INVOICE'::character varying::text, 'PAYMENT'::character varying::text, 'CREDIT_NOTE'::character varying::text, 'DEBIT_NOTE'::character varying::text, 'ADJUSTMENT'::character varying::text])),
  amount numeric NOT NULL,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  transaction_date timestamp with time zone,
  payment_method USER-DEFINED,
  payment_status USER-DEFINED,
  balance_after_transaction numeric,
  CONSTRAINT client_transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT client_transactions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id),
  CONSTRAINT client_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.clients (
  client_id bigint NOT NULL DEFAULT nextval('clients_client_id_seq'::regclass),
  full_name character varying NOT NULL,
  email character varying,
  phone character varying,
  document_number character varying,
  address text,
  city character varying,
  province character varying,
  postal_code character varying,
  country character varying DEFAULT 'Argentina'::character varying,
  has_credit boolean DEFAULT false,
  credit_limit numeric DEFAULT 0,
  current_balance numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  last_transaction_date timestamp with time zone,
  tax_condition USER-DEFINED NOT NULL DEFAULT 'FINAL_CONSUMER'::tax_condition_type,
  billing_enabled boolean NOT NULL DEFAULT true,
  available_credit numeric NOT NULL DEFAULT 0,
  tax_ident text,
  short_code smallint,
  organization_id uuid,
  CONSTRAINT clients_pkey PRIMARY KEY (client_id),
  CONSTRAINT clients_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.disabled_prices (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  price_id bigint NOT NULL,
  location_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT disabled_prices_pkey PRIMARY KEY (id),
  CONSTRAINT disabled_prices_price_id_fkey FOREIGN KEY (price_id) REFERENCES public.prices(price_id),
  CONSTRAINT disabled_prices_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id)
);
CREATE TABLE public.enabled_prices_clients (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  price_id bigint NOT NULL,
  client_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enabled_prices_clients_pkey PRIMARY KEY (id),
  CONSTRAINT enabled_prices_clients_price_id_fkey FOREIGN KEY (price_id) REFERENCES public.prices(price_id),
  CONSTRAINT enabled_prices_clients_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.iva (
  iva_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  iva_number smallint NOT NULL,
  iva_percentege smallint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT iva_pkey PRIMARY KEY (iva_id),
  CONSTRAINT iva_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.load_orders (
  load_order_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  recieved_by uuid,
  recieved_by_other text,
  invoice_number bigint,
  load_order_number bigint,
  provider_id bigint,
  delivery_date timestamp with time zone,
  receptor_id uuid,
  receptor_other text,
  transporter_data jsonb,
  status text,
  observations text,
  total_download_cost numeric,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT load_orders_pkey PRIMARY KEY (load_order_id),
  CONSTRAINT load_orders_recieved_by_fkey FOREIGN KEY (recieved_by) REFERENCES public.users(id),
  CONSTRAINT load_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id),
  CONSTRAINT load_orders_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT load_orders_receptor_id_fkey FOREIGN KEY (receptor_id) REFERENCES public.users(id)
);
CREATE TABLE public.locations (
  location_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  type text NOT NULL,
  address text,
  name text,
  deleted_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT locations_pkey PRIMARY KEY (location_id),
  CONSTRAINT locations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.lot_containers (
  lot_container_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  lot_container_name text,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone,
  lot_container_price bigint,
  organization_id uuid,
  CONSTRAINT lot_containers_pkey PRIMARY KEY (lot_container_id),
  CONSTRAINT lot_containers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.lot_containers_movements (
  lot_container_movement_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  quantity bigint,
  from_location_id bigint,
  to_location_id bigint,
  from_provider_id bigint,
  to_provider_id bigint,
  from_client_id bigint,
  to_client_id bigint,
  lot_container_id bigint,
  status USER-DEFINED,
  CONSTRAINT lot_containers_movements_pkey PRIMARY KEY (lot_container_movement_id),
  CONSTRAINT lot_containers_movements_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES public.locations(location_id),
  CONSTRAINT lot_container_movement_from_provider_id_fkey FOREIGN KEY (from_provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT lot_container_movement_to_provider_id_fkey FOREIGN KEY (to_provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT lot_container_movement_from_client_id_fkey FOREIGN KEY (from_client_id) REFERENCES public.clients(client_id),
  CONSTRAINT lot_container_movement_to_client_id_fkey FOREIGN KEY (to_client_id) REFERENCES public.clients(client_id),
  CONSTRAINT lot_container_movements_lot_container_id_fkey FOREIGN KEY (lot_container_id) REFERENCES public.lot_containers(lot_container_id),
  CONSTRAINT lot_containers_movements_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES public.locations(location_id)
);
CREATE TABLE public.lot_containers_stock (
  lot_containers_stock_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  lot_container_id bigint,
  quantity bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint,
  provider_id bigint,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  stock_id bigint,
  location_id bigint,
  organization_id uuid,
  CONSTRAINT lot_containers_stock_pkey PRIMARY KEY (lot_containers_stock_id),
  CONSTRAINT lot_containers_stock_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT lot_containers_stock_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id),
  CONSTRAINT lot_containers_location_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id),
  CONSTRAINT lot_containers_location_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT lot_containers_location_lot_container_id_fkey FOREIGN KEY (lot_container_id) REFERENCES public.lot_containers(lot_container_id),
  CONSTRAINT lot_containers_location_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id)
);
CREATE TABLE public.lot_traces (
  lot_trace_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  lot_from_id bigint NOT NULL,
  lot_to_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lot_traces_pkey PRIMARY KEY (lot_trace_id),
  CONSTRAINT lot_traces_lot_from_fk FOREIGN KEY (lot_from_id) REFERENCES public.lots(lot_id),
  CONSTRAINT lot_traces_lot_to_fk FOREIGN KEY (lot_to_id) REFERENCES public.lots(lot_id)
);
CREATE TABLE public.lots (
  lot_id smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
  provider_id bigint,
  expiration_date date,
  expiration_date_notification boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  initial_stock_quantity numeric,
  is_sold_out boolean,
  is_expired boolean,
  load_order_id bigint,
  product_id bigint,
  purchase_cost_total numeric,
  purchase_cost_per_unit numeric,
  download_total_cost numeric,
  download_cost_per_unit numeric,
  final_cost_total numeric,
  final_cost_per_unit numeric,
  purchase_cost_per_bulk numeric,
  download_cost_per_bulk numeric,
  final_cost_per_bulk numeric,
  delivery_cost_total numeric,
  delivery_cost_per_unit numeric,
  delivery_cost_per_bulk numeric,
  productor_commission_type USER-DEFINED NOT NULL DEFAULT 'NONE'::commission_type,
  productor_commission_percentage numeric,
  productor_commission_unit_value numeric,
  purchasing_agent_id integer,
  purchasing_agent_commision_type USER-DEFINED NOT NULL DEFAULT 'NONE'::commission_type,
  purchasing_agent_commision_percentage numeric,
  purchasing_agent_commision_unit_value numeric,
  extra_cost_total numeric,
  is_finished boolean,
  CONSTRAINT lots_pkey PRIMARY KEY (lot_id),
  CONSTRAINT lots_load_order_id_fkey FOREIGN KEY (load_order_id) REFERENCES public.load_orders(load_order_id),
  CONSTRAINT lots_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.notifications (
  notification_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text,
  title text,
  message text,
  order_id bigint,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  canceled_by uuid,
  location_id bigint,
  organization_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (notification_id),
  CONSTRAINT notifications_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT notifications_canceled_by_fkey FOREIGN KEY (canceled_by) REFERENCES public.users(id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.order_items (
  order_item_id bigint NOT NULL DEFAULT nextval('order_items_order_item_id_seq'::regclass),
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  quantity numeric NOT NULL,
  price numeric NOT NULL,
  total numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  subtotal bigint,
  discount bigint,
  tax bigint,
  is_deleted boolean,
  logic_type USER-DEFINED,
  product_presentation_id bigint,
  stock_id bigint,
  status USER-DEFINED,
  location_id bigint,
  lot_id smallint,
  over_sell_quantity numeric,
  updated_at timestamp with time zone,
  qty_in_base_units numeric,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
  CONSTRAINT order_items_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT order_items_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.lots(lot_id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT order_items_product_presentation_id_fkey FOREIGN KEY (product_presentation_id) REFERENCES public.product_presentations(product_presentation_id),
  CONSTRAINT order_items_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id)
);
CREATE TABLE public.orders (
  order_id bigint NOT NULL DEFAULT nextval('orders_order_id_seq'::regclass),
  location_id bigint,
  client_id bigint,
  provider_id bigint,
  order_number bigint NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0,
  discount numeric NOT NULL DEFAULT 0,
  tax numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  currency character varying DEFAULT 'ARS'::character varying,
  notes text,
  delivery_date timestamp without time zone,
  created_at timestamp with time zone,
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  client_type USER-DEFINED,
  payment_status USER-DEFINED,
  order_status USER-DEFINED DEFAULT 'NEW'::order_status,
  order_type USER-DEFINED,
  organization_id uuid,
  terminal_session_id bigint,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT orders_terminal_session_id_fkey FOREIGN KEY (terminal_session_id) REFERENCES public.terminal_sessions(terminal_session_id),
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id),
  CONSTRAINT orders_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.organizations (
  organization_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  organization_name text,
  max_terminals numeric DEFAULT '1'::numeric,
  CONSTRAINT organizations_pkey PRIMARY KEY (organization_id)
);
CREATE TABLE public.payments (
  payment_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  order_id bigint,
  amount bigint,
  payment_method USER-DEFINED,
  payment_type USER-DEFINED,
  payment_direction USER-DEFINED,
  client_id bigint,
  provider_id bigint,
  terminal_session_id bigint,
  CONSTRAINT payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT payments_terminal_session_fk FOREIGN KEY (terminal_session_id) REFERENCES public.terminal_sessions(terminal_session_id),
  CONSTRAINT payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id),
  CONSTRAINT payments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT order_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.prices (
  price_number bigint,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  price numeric,
  logic_type USER-DEFINED,
  qty_per_price numeric,
  profit_percentage numeric,
  observations text,
  product_presentation_id bigint,
  location_id bigint,
  CONSTRAINT prices_pkey PRIMARY KEY (price_id),
  CONSTRAINT prices_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT prices_product_presentation_id_fkey FOREIGN KEY (product_presentation_id) REFERENCES public.product_presentations(product_presentation_id)
);
CREATE TABLE public.product_presentations (
  product_presentation_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_presentation_name text,
  short_code bigint,
  product_id bigint,
  deleted_at timestamp with time zone,
  bulk_quantity_equivalence numeric,
  updated_at timestamp with time zone,
  sell_type USER-DEFINED,
  organization_id uuid,
  CONSTRAINT product_presentations_pkey PRIMARY KEY (product_presentation_id),
  CONSTRAINT product_presentations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id),
  CONSTRAINT product_presentations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.products (
  product_name text NOT NULL,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  barcode bigint,
  short_code bigint,
  product_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  category_id bigint,
  sub_category_id bigint,
  provider_id bigint,
  allow_stock_control boolean,
  brand_id bigint,
  public_image_id bigint,
  product_description text,
  observations text,
  parent_product_id bigint,
  lot_control boolean,
  iva_id bigint,
  organization_id uuid,
  CONSTRAINT products_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id),
  CONSTRAINT products_sub_category_id_fkey FOREIGN KEY (sub_category_id) REFERENCES public.sub_categories(sub_category_id),
  CONSTRAINT products_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(provider_id),
  CONSTRAINT products_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id),
  CONSTRAINT products_public_image_id_fkey FOREIGN KEY (public_image_id) REFERENCES public.public_images(public_image_id),
  CONSTRAINT products_parent_product_id_fkey FOREIGN KEY (parent_product_id) REFERENCES public.products(product_id),
  CONSTRAINT products_iva_id_fkey FOREIGN KEY (iva_id) REFERENCES public.iva(iva_id),
  CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.providers (
  provider_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_At timestamp with time zone,
  deleted_at timestamp with time zone,
  provider_name text,
  short_code bigint,
  organization_id uuid,
  CONSTRAINT providers_pkey PRIMARY KEY (provider_id),
  CONSTRAINT providers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.public_images (
  public_image_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  public_image_src text NOT NULL,
  public_image_category text NOT NULL,
  public_image_name text NOT NULL,
  CONSTRAINT public_images_pkey PRIMARY KEY (public_image_id)
);
CREATE TABLE public.purchasing_agents (
  purchasing_agent_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  purchasing_agent_name text,
  business_owner_id uuid,
  CONSTRAINT purchasing_agents_pkey PRIMARY KEY (purchasing_agent_id),
  CONSTRAINT purchasing_agent_business_owner_id_fkey FOREIGN KEY (business_owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.stock (
  stock_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  lot_id bigint NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  min_notification numeric DEFAULT 0,
  max_notification numeric DEFAULT 0,
  transformed_from_product_id bigint,
  transformed_to_product_id bigint,
  stock_type USER-DEFINED,
  product_id bigint,
  reserved_for_transferring_quantity numeric,
  reserved_for_selling_quantity numeric,
  location_id bigint,
  is_closed boolean DEFAULT false,
  over_sell_quantity numeric,
  CONSTRAINT stock_pkey PRIMARY KEY (stock_id),
  CONSTRAINT stock_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT stock_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.lots(lot_id)
);
CREATE TABLE public.stock_movements (
  stock_movement_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  lot_id bigint,
  movement_type USER-DEFINED,
  quantity numeric,
  to_location_id bigint,
  should_notify_owner boolean,
  from_location_id bigint,
  price numeric,
  business_owner_id uuid,
  created_by uuid,
  stock_id bigint,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (stock_movement_id),
  CONSTRAINT stock_movements_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES public.locations(location_id),
  CONSTRAINT stock_movements_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES public.locations(location_id),
  CONSTRAINT stock_movements_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id),
  CONSTRAINT stock_movements_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.lots(lot_id),
  CONSTRAINT stock_movements_business_owner_id_fkey FOREIGN KEY (business_owner_id) REFERENCES public.users(id),
  CONSTRAINT stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.store_order_sequences (
  store_order_sequence_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  location_id bigint UNIQUE,
  last_number bigint,
  CONSTRAINT store_order_sequences_pkey PRIMARY KEY (store_order_sequence_id),
  CONSTRAINT store_order_sequences_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id)
);
CREATE TABLE public.sub_categories (
  sub_category_name character varying NOT NULL,
  slug character varying,
  description text,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  sub_category_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  business_owner_id uuid NOT NULL,
  CONSTRAINT sub_categories_pkey PRIMARY KEY (sub_category_id),
  CONSTRAINT sub_categories_business_owner_id_fkey FOREIGN KEY (business_owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.terminal_sessions (
  terminal_session_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  organization_id uuid NOT NULL,
  terminal_id bigint NOT NULL,
  opened_by_user_id uuid NOT NULL,
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  opening_balance numeric NOT NULL DEFAULT 0,
  closing_balance numeric,
  status text NOT NULL DEFAULT 'OPEN'::text,
  location_id bigint,
  CONSTRAINT terminal_sessions_pkey PRIMARY KEY (terminal_session_id),
  CONSTRAINT terminal_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id),
  CONSTRAINT terminal_sessions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_sessions_opened_by_user_fkey FOREIGN KEY (opened_by_user_id) REFERENCES public.users(id),
  CONSTRAINT terminal_sessions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id)
);
CREATE TABLE public.terminals (
  terminal_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT terminals_pkey PRIMARY KEY (terminal_id),
  CONSTRAINT terminals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.transfer_order_items (
  transfer_order_item_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transfer_order_id bigint,
  product_id bigint,
  quantity numeric,
  product_presentation_id bigint,
  status USER-DEFINED,
  stock_id bigint,
  lot_containers_movement_id bigint,
  updated_at timestamp with time zone,
  lot_id smallint,
  is_transferred boolean,
  CONSTRAINT transfer_order_items_pkey PRIMARY KEY (transfer_order_item_id),
  CONSTRAINT transfer_order_items_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.lots(lot_id),
  CONSTRAINT transfer_order_items_product_presentation_id_fkey FOREIGN KEY (product_presentation_id) REFERENCES public.product_presentations(product_presentation_id),
  CONSTRAINT transfer_order_items_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id),
  CONSTRAINT transfer_order_items_lot_containers_movement_id_fkey FOREIGN KEY (lot_containers_movement_id) REFERENCES public.lot_containers_movements(lot_container_movement_id),
  CONSTRAINT foi_transfer_order_fk FOREIGN KEY (transfer_order_id) REFERENCES public.transfer_orders(transfer_order_id),
  CONSTRAINT foi_product_fk FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.transfer_orders (
  transfer_order_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_user_id uuid,
  notes text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::movement_status,
  from_location_id bigint,
  to_location_id bigint,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT transfer_orders_pkey PRIMARY KEY (transfer_order_id),
  CONSTRAINT transfer_orders_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES public.locations(location_id),
  CONSTRAINT transfer_orders_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES public.locations(location_id),
  CONSTRAINT transfer_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id),
  CONSTRAINT transfer_orders_assigned_user_fk FOREIGN KEY (assigned_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.transformation_items (
  transformation_item_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_id bigint,
  product_presentation_id bigint,
  lot_id bigint,
  stock_id bigint,
  is_origin boolean NOT NULL DEFAULT false,
  quantity numeric,
  max_quantity numeric,
  bulk_quantity_equivalence numeric,
  final_cost_per_unit numeric,
  final_cost_per_bulk numeric,
  final_cost_total numeric,
  location_id bigint,
  transformation_id bigint,
  CONSTRAINT transformation_items_pkey PRIMARY KEY (transformation_item_id),
  CONSTRAINT transformation_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT transformation_items_product_presentation_id_fkey FOREIGN KEY (product_presentation_id) REFERENCES public.product_presentations(product_presentation_id),
  CONSTRAINT transformation_items_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.lots(lot_id),
  CONSTRAINT transformation_items_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stock(stock_id),
  CONSTRAINT transformation_items_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT transformation_items_transformation_id_fkey FOREIGN KEY (transformation_id) REFERENCES public.transformations(transformation_id)
);
CREATE TABLE public.transformations (
  transformation_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transformation_cost numeric,
  notes text,
  CONSTRAINT transformations_pkey PRIMARY KEY (transformation_id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL,
  full_name character varying,
  phone character varying,
  address jsonb,
  role USER-DEFINED NOT NULL DEFAULT 'OWNER'::user_role_enum,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  business_owner_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  short_code smallint,
  organization_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_business_owner_id_fkey FOREIGN KEY (business_owner_id) REFERENCES public.users(id),
  CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(organization_id)
);
CREATE TABLE public.website_preferences (
  id uuid NOT NULL,
  theme character varying DEFAULT 'default'::character varying,
  primary_color character varying DEFAULT '#6b99fe'::character varying,
  secondary_color character varying DEFAULT '#f4b700'::character varying,
  logo_url text,
  favicon_url text,
  homepage_layout jsonb,
  custom_css text,
  language character varying DEFAULT 'es'::character varying,
  currency character varying DEFAULT 'USD'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT website_preferences_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);